// ---------- Shared destination / holiday package data ----------
// Used by destinations.html (listing) and package.html (detail template).
// priceType: "vehicle" = flat price for the car for a day trip,
//            "person"  = starting price per person, twin sharing, for a multi-day package.

const DESTINATIONS = [
  {
    slug: "mysuru",
    name: "Mysuru",
    category: "Heritage City",
    meta: "145 km · ~3.5 hrs · Full-day trip",
    tagline: "Palaces, gardens and royal history, in a single day from Bengaluru.",
    heroImg: "1590766940554-634a7ed41450",
    gallery: ["1590766940554-634a7ed41450", "1600011689032-8b628b8a8747", "1602216056096-3b40cc0c9944"],
    duration: "1 Day",
    priceType: "vehicle",
    price: 3500,
    priceNote: "per sedan, full day (AC, driver, fuel, tolls & parking included)",
    bestTime: "October to March",
    pickup: "Bengaluru (any area)",
    highlights: [
      "Mysore Palace, with the evening illumination on Sundays and public holidays",
      "Chamundi Hills viewpoint and temple",
      "Brindavan Gardens musical fountain show",
      "St. Philomena's Church",
      "Time for silk-saree and sandalwood shopping",
    ],
    itinerary: [
      { day: "Day 1", title: "Bengaluru → Mysuru → Bengaluru", desc: "Early start from Bengaluru, arrive Mysuru by late morning. Visit Mysore Palace, Chamundi Hills and St. Philomena's Church. Lunch break. Evening at Brindavan Gardens for the fountain show, then drive back, arriving late evening." },
    ],
    inclusions: ["AC vehicle for the full day", "Driver allowance", "Tolls & parking", "Bottled water"],
    exclusions: ["Monument entry tickets", "Meals", "Guide charges"],
  },
  {
    slug: "goa",
    name: "Goa",
    category: "Beach Getaway",
    meta: "560 km · ~10 hrs · 3N / 4D package",
    tagline: "Beaches, seafood and a relaxed coastal pace, 3 nights of it.",
    heroImg: "1512343879784-a960bf40e7f2",
    gallery: ["1512343879784-a960bf40e7f2", "1600011689032-8b628b8a8747", "1602216056096-3b40cc0c9944"],
    duration: "3 Nights / 4 Days",
    priceType: "person",
    price: 10999,
    priceNote: "per person, twin sharing (land package; airfare/train extra)",
    bestTime: "November to February",
    pickup: "Bengaluru or Goa airport/station",
    highlights: [
      "North and South Goa beach circuits",
      "Fort Aguada and Basilica of Bom Jesus",
      "Sunset cruise on the Mandovi river",
      "Free time at Baga / Calangute / Palolem",
      "Local seafood thali experience",
    ],
    itinerary: [
      { day: "Day 1", title: "Arrival & North Goa beaches", desc: "Pick-up on arrival, check-in, evening at Calangute and Baga beach." },
      { day: "Day 2", title: "Old Goa & Fort Aguada", desc: "Basilica of Bom Jesus, Fort Aguada, free time, evening Mandovi river cruise." },
      { day: "Day 3", title: "South Goa", desc: "Palolem / Colva beach day trip, free time for water sports (optional, paid)." },
      { day: "Day 4", title: "Departure", desc: "Breakfast, check-out, drop to airport/station." },
    ],
    inclusions: ["3 nights hotel stay with breakfast", "AC vehicle for all transfers & sightseeing", "Mandovi river cruise ticket", "Driver allowance, tolls & parking"],
    exclusions: ["Airfare / train fare", "Lunch & dinner (except where noted)", "Water sports & entry tickets"],
  },
  {
    slug: "alleppey",
    name: "Alleppey",
    category: "Backwaters",
    meta: "3N / 4D package · Houseboat included",
    tagline: "A night on a houseboat, drifting through Kerala's backwaters.",
    heroImg: "1593693397690-362cb9666fc2",
    gallery: ["1593693397690-362cb9666fc2", "1602216056096-3b40cc0c9944", "1600011689032-8b628b8a8747"],
    duration: "3 Nights / 4 Days",
    priceType: "person",
    price: 13499,
    priceNote: "per person, twin sharing (includes 1 night houseboat)",
    bestTime: "September to March",
    pickup: "Bengaluru or Kochi airport",
    highlights: [
      "Overnight stay on a traditional Kerala houseboat",
      "Backwater cruise through coconut-lined canals",
      "Kumarakom bird sanctuary visit",
      "Traditional Kerala sadya meal on the houseboat",
      "Village and coir-making walk",
    ],
    itinerary: [
      { day: "Day 1", title: "Arrival → Alleppey", desc: "Pick-up, drive to Alleppey, board the houseboat by afternoon for an overnight backwater cruise." },
      { day: "Day 2", title: "Houseboat → Kumarakom", desc: "Disembark after breakfast, transfer to a resort near Kumarakom, visit the bird sanctuary." },
      { day: "Day 3", title: "Leisure day", desc: "Village walk, canoe ride through narrow canals (optional, paid), free time at the resort." },
      { day: "Day 4", title: "Departure", desc: "Breakfast, check-out, drop to airport/station." },
    ],
    inclusions: ["1 night houseboat (all meals onboard)", "2 nights resort stay with breakfast", "AC vehicle for all transfers", "Kumarakom bird sanctuary entry"],
    exclusions: ["Airfare / train fare", "Lunch & dinner on land days", "Canoe rides & other paid activities"],
  },
  {
    slug: "madurai",
    name: "Madurai",
    category: "Pilgrimage",
    meta: "435 km · ~8 hrs · 2N / 3D package",
    tagline: "Temple towers, deep tradition and classic Tamil Nadu cuisine.",
    heroImg: "1582510003544-4d00b7f74220",
    gallery: ["1582510003544-4d00b7f74220", "1602216056096-3b40cc0c9944", "1600011689032-8b628b8a8747"],
    duration: "2 Nights / 3 Days",
    priceType: "person",
    price: 7999,
    priceNote: "per person, twin sharing",
    bestTime: "November to February",
    pickup: "Bengaluru",
    highlights: [
      "Meenakshi Amman Temple, including the evening ritual",
      "Thirumalai Nayakkar Mahal",
      "Alagar Kovil and the Vaigai riverside",
      "Local Chettinad-style meals",
      "Optional add-on to Rameswaram (2 more days)",
    ],
    itinerary: [
      { day: "Day 1", title: "Bengaluru → Madurai", desc: "Overnight or early drive, check-in, evening visit to Meenakshi Amman Temple." },
      { day: "Day 2", title: "Madurai sightseeing", desc: "Thirumalai Nayakkar Mahal, Gandhi Memorial Museum, Alagar Kovil, evening free for local markets." },
      { day: "Day 3", title: "Departure", desc: "Breakfast, check-out, drive back to Bengaluru." },
    ],
    inclusions: ["2 nights hotel stay with breakfast", "AC vehicle throughout", "Driver allowance, tolls & parking"],
    exclusions: ["Lunch & dinner", "Temple donation tickets / special darshan", "Rameswaram add-on (quoted separately)"],
  },
  {
    slug: "kumarakom",
    name: "Kumarakom",
    category: "Nature Retreat",
    meta: "2N / 3D package · Backwater resort",
    tagline: "A quiet resort stay among palm-fringed canals and paddy fields.",
    heroImg: "1602216056096-3b40cc0c9944",
    gallery: ["1602216056096-3b40cc0c9944", "1593693397690-362cb9666fc2", "1600011689032-8b628b8a8747"],
    duration: "2 Nights / 3 Days",
    priceType: "person",
    price: 11499,
    priceNote: "per person, twin sharing",
    bestTime: "September to March",
    pickup: "Bengaluru or Kochi airport",
    highlights: [
      "Kumarakom Bird Sanctuary",
      "Backwater canoe & shikara rides",
      "Vembanad Lake sunset point",
      "Ayurvedic massage (optional add-on)",
      "Toddy-shop style Kerala lunch",
    ],
    itinerary: [
      { day: "Day 1", title: "Arrival → Kumarakom", desc: "Pick-up, drive in, check-in at a backwater resort, evening at leisure by the lake." },
      { day: "Day 2", title: "Bird sanctuary & canals", desc: "Morning visit to the bird sanctuary, afternoon shikara ride through the canals." },
      { day: "Day 3", title: "Departure", desc: "Breakfast, check-out, drop to airport/station." },
    ],
    inclusions: ["2 nights resort stay with breakfast", "Bird sanctuary entry", "One shikara ride", "AC vehicle for all transfers"],
    exclusions: ["Airfare / train fare", "Lunch & dinner", "Ayurvedic spa treatments"],
  },
  {
    slug: "agra",
    name: "Agra",
    category: "Golden Triangle",
    meta: "5N / 6D package · Delhi · Agra · Jaipur",
    tagline: "The Taj Mahal, anchoring a classic Golden Triangle circuit.",
    heroImg: "1564507592333-c60657eea523",
    gallery: ["1564507592333-c60657eea523", "1524492412937-b28074a5d7da", "1477587458883-47145ed94245"],
    duration: "5 Nights / 6 Days",
    priceType: "person",
    price: 18999,
    priceNote: "per person, twin sharing (Delhi–Agra–Jaipur circuit)",
    bestTime: "October to March",
    pickup: "Delhi airport/station",
    highlights: [
      "Taj Mahal at sunrise",
      "Agra Fort",
      "Fatehpur Sikri en route to Jaipur",
      "Combined with Jaipur's forts and palaces",
      "Old & New Delhi sightseeing",
    ],
    itinerary: [
      { day: "Day 1", title: "Arrival in Delhi", desc: "Pick-up from the airport/station, check-in, evening at leisure or Old Delhi food walk (optional)." },
      { day: "Day 2", title: "Delhi sightseeing", desc: "Red Fort, Jama Masjid, India Gate, Qutub Minar, Humayun's Tomb." },
      { day: "Day 3", title: "Delhi → Agra", desc: "Drive to Agra, sunrise or evening visit to the Taj Mahal, Agra Fort." },
      { day: "Day 4", title: "Agra → Jaipur", desc: "Fatehpur Sikri en route, continue to Jaipur, evening at leisure." },
      { day: "Day 5", title: "Jaipur sightseeing", desc: "Amber Fort, City Palace, Hawa Mahal, Jantar Mantar." },
      { day: "Day 6", title: "Departure", desc: "Breakfast, drop to Jaipur airport/station." },
    ],
    inclusions: ["5 nights hotel stay with breakfast", "AC vehicle for the full circuit", "Driver allowance, tolls, parking & interstate permits"],
    exclusions: ["Airfare / train fare", "Monument entry tickets", "Lunch & dinner"],
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    category: "Royal Heritage",
    meta: "4N / 5D package · The Pink City",
    tagline: "Forts, palaces and bazaars across Rajasthan's capital and nearby towns.",
    heroImg: "1477587458883-47145ed94245",
    gallery: ["1477587458883-47145ed94245", "1600011689032-8b628b8a8747", "1602216056096-3b40cc0c9944"],
    duration: "4 Nights / 5 Days",
    priceType: "person",
    price: 15999,
    priceNote: "per person, twin sharing",
    bestTime: "October to March",
    pickup: "Jaipur airport/station",
    highlights: [
      "Amber Fort with an elephant or jeep ride up",
      "City Palace and the Hawa Mahal facade",
      "Jantar Mantar observatory",
      "Nahargarh Fort at sunset",
      "Bazaar time for block-print textiles and jewellery",
    ],
    itinerary: [
      { day: "Day 1", title: "Arrival in Jaipur", desc: "Pick-up, check-in, evening at Nahargarh Fort for the city view at sunset." },
      { day: "Day 2", title: "Amber Fort & City Palace", desc: "Morning at Amber Fort, afternoon City Palace, Hawa Mahal and Jantar Mantar." },
      { day: "Day 3", title: "Local day trip", desc: "Optional excursion to Abhaneri Stepwell or Samode, or a free bazaar day." },
      { day: "Day 4", title: "Leisure & shopping", desc: "Free morning, afternoon at Johari Bazaar / Bapu Bazaar for shopping." },
      { day: "Day 5", title: "Departure", desc: "Breakfast, check-out, drop to airport/station." },
    ],
    inclusions: ["4 nights hotel stay with breakfast", "AC vehicle throughout", "Driver allowance, tolls & parking"],
    exclusions: ["Monument entry tickets", "Elephant / jeep ride at Amber Fort", "Lunch & dinner"],
  },
  {
    slug: "manali",
    name: "Manali",
    category: "Himalayas",
    meta: "5N / 6D package · Manali · Solang · Kasol",
    tagline: "Snow peaks, river valleys and mountain air, deep in Himachal.",
    heroImg: "1549880338-65ddcdfd017b",
    gallery: ["1549880338-65ddcdfd017b", "1609920658906-8223bd289001", "1506905925346-21bda4d32df4"],
    duration: "5 Nights / 6 Days",
    priceType: "person",
    price: 16999,
    priceNote: "per person, twin sharing",
    bestTime: "March to June, December to February for snow",
    pickup: "Chandigarh airport/station",
    highlights: [
      "Solang Valley cable car & snow activities",
      "Old Manali and the Hidimba Devi Temple",
      "Day trip to Kasol and the Parvati Valley",
      "Rohtang Pass (season-dependent, permit required)",
      "Riverside cafés along the Beas",
    ],
    itinerary: [
      { day: "Day 1", title: "Chandigarh → Manali", desc: "Pick-up, scenic drive through the Kullu valley, check-in at Manali." },
      { day: "Day 2", title: "Solang Valley", desc: "Cable car ride, snow/adventure activities (optional, paid), evening at Mall Road." },
      { day: "Day 3", title: "Old Manali & temples", desc: "Hidimba Devi Temple, Old Manali cafés, Vashisht hot springs." },
      { day: "Day 4", title: "Kasol day trip", desc: "Drive to Kasol and Manikaran, riverside time, return to Manali by evening." },
      { day: "Day 5", title: "Rohtang Pass (seasonal)", desc: "Subject to permit and weather; alternate local sightseeing if closed." },
      { day: "Day 6", title: "Departure", desc: "Breakfast, drive back to Chandigarh for drop-off." },
    ],
    inclusions: ["5 nights hotel stay with breakfast", "AC/non-AC vehicle suited to mountain roads", "Driver allowance, tolls & parking"],
    exclusions: ["Airfare / train fare", "Rohtang permit fee", "Adventure activities", "Lunch & dinner"],
  },
  {
    slug: "ooty",
    name: "Ooty",
    category: "Hill Station",
    meta: "270 km · ~6.5 hrs · 2N / 3D package",
    tagline: "Tea gardens, cool air and the Nilgiri hills, a short way from Bengaluru.",
    heroImg: "1506905925346-21bda4d32df4",
    gallery: ["1506905925346-21bda4d32df4", "1600011689032-8b628b8a8747", "1602216056096-3b40cc0c9944"],
    duration: "2 Nights / 3 Days",
    priceType: "person",
    price: 6999,
    priceNote: "per person, twin sharing",
    bestTime: "October to June",
    pickup: "Bengaluru",
    highlights: [
      "Nilgiri Mountain Railway (toy train, seasonal, subject to availability)",
      "Botanical Gardens and Ooty Lake boating",
      "Doddabetta Peak viewpoint",
      "Tea estate visit and tasting",
      "Coonoor day trip (optional)",
    ],
    itinerary: [
      { day: "Day 1", title: "Bengaluru → Ooty", desc: "Drive through Bandipur/Mudumalai forest, check-in, evening at Ooty Lake." },
      { day: "Day 2", title: "Ooty sightseeing", desc: "Botanical Gardens, Doddabetta Peak, a tea estate visit, Rose Garden." },
      { day: "Day 3", title: "Departure", desc: "Breakfast, optional Coonoor stop, drive back to Bengaluru." },
    ],
    inclusions: ["2 nights hotel stay with breakfast", "AC vehicle throughout", "Driver allowance, tolls & parking"],
    exclusions: ["Lunch & dinner", "Boating & toy train tickets", "Tea estate tasting fee"],
  },
];

// Helper shared by destinations.html and package.html
function destImg(id, w = 900) {
  return `https://images.unsplash.com/photo-${id}?w=${w}&q=70&auto=format&fit=crop`;
}
